/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.Encounter;
import model.Hospital;
import model.House;
import model.HospitalDirectory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.Doctor;
import model.DoctorDirectory;

/**
 *
 * @author rajmehta
 */
public class CommunityAdministratorPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdministratorPanel
     */
    City city;
    DefaultTableModel model;
    DefaultTableModel model1;
    String[] communityDropboxList;
    String selectedCommunity;
    Community community;
    Hospital hospital;
    House house;
    HospitalDirectory  hospitalDirectory;
    PersonDirectory pd;
    DoctorDirectory docDir;
    Hospital selectedHospital;
    Person selectedPerson;
    PatientDirectory patDir;
    
    public CommunityAdministratorPanel() {
        initComponents();
    }
    
    public CommunityAdministratorPanel(City city, String[] communityDropboxList, PatientDirectory patDir, HospitalDirectory hospDir, PersonDirectory pd, DoctorDirectory docDir) {
        initComponents();
        this.city = city;
        this.communityDropboxList = communityDropboxList;
        this.pd=pd;
        this.docDir=docDir;
        this.hospitalDirectory = hospDir;
        this.patDir = patDir;
        
        community_dropbox.removeAllItems();

        for(Community c: city.getCommList()){
            community_dropbox.addItem(c.getCommName());
        }
    

    model = (DefaultTableModel) hospital_table.getModel();
    model1 = (DefaultTableModel) house_table.getModel();
    
    /////////////
    ArrayList<Integer> aa = new ArrayList<Integer>();
            
    for(Community c: city.getCommList()){
        for(Hospital h: c.getHospitalList()){
            aa.add(h.getHospNum());
        }      
    }
            
    hopital_list.removeAllItems();
      
    for(int s:aa){
       hopital_list.addItem(String.valueOf(s));
    }
    ////////////

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        landingPanel = new javax.swing.JPanel();
        update_hospital = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hospital_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        update_hospital_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        house_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        house_dropbox = new javax.swing.JComboBox<>();
        community_dropbox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        update_house = new javax.swing.JTextField();
        create_hospital_btn = new javax.swing.JButton();
        update_house_btn = new javax.swing.JButton();
        create_new_house = new javax.swing.JButton();
        search_comm_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        hospital_dropbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        managePatientsButton = new javax.swing.JButton();
        manageDoctorsButton = new javax.swing.JButton();
        manageDoctorsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        doctor_table = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        doctor_name = new javax.swing.JTextField();
        doctor_cellno = new javax.swing.JTextField();
        doctor_birthdate = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        persontable = new javax.swing.JTable();
        save_updateddoctor = new javax.swing.JButton();
        add_doctorBtn = new javax.swing.JButton();
        populatetables = new javax.swing.JButton();
        hopital_list = new javax.swing.JComboBox<>();
        houseJPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        hospNum1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        streetNamehos = new javax.swing.JTextField();
        communityTextField1 = new javax.swing.JTextField();
        zipcodeTextField1 = new javax.swing.JTextField();
        saveHouseDetails = new javax.swing.JButton();
        cityJTextField1 = new javax.swing.JTextField();
        hospitalJPanel = new javax.swing.JPanel();
        zipcodeTextField = new javax.swing.JTextField();
        communityTextField = new javax.swing.JTextField();
        streetName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hospNum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        saveHospDetails = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel7.setText("Houses in Community:");

        hospital_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hosp num", "StreetName", "City", "ZipCode", "No of Docs"
            }
        ));
        jScrollPane1.setViewportView(hospital_table);

        jLabel4.setText("New Value:");

        jLabel8.setText("Hospitals in Community:");

        update_hospital_btn.setText("Update Hospital");
        update_hospital_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_hospital_btnActionPerformed(evt);
            }
        });

        house_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "House Num", "Street Name", "City", "No of members"
            }
        ));
        jScrollPane2.setViewportView(house_table);

        jLabel5.setText("Modify:");

        house_dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "houseUnit", "streetName" }));

        community_dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("New Value:");

        jLabel2.setText("Communities");

        create_hospital_btn.setText("Create New Hospital");
        create_hospital_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_hospital_btnActionPerformed(evt);
            }
        });

        update_house_btn.setText("Update House");
        update_house_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_house_btnActionPerformed(evt);
            }
        });

        create_new_house.setText("Create New House");
        create_new_house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_new_houseActionPerformed(evt);
            }
        });

        search_comm_btn.setText("Search");
        search_comm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_comm_btnActionPerformed(evt);
            }
        });

        jLabel3.setText("Modify:");

        hospital_dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "streetName", "zipCode" }));

        jLabel1.setFont(new java.awt.Font("Zapfino", 0, 18)); // NOI18N
        jLabel1.setText("Modify the information under a Community");

        managePatientsButton.setText("Manage Patients");
        managePatientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientsButtonActionPerformed(evt);
            }
        });

        manageDoctorsButton.setText("Manage Doctors");
        manageDoctorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout landingPanelLayout = new javax.swing.GroupLayout(landingPanel);
        landingPanel.setLayout(landingPanelLayout);
        landingPanelLayout.setHorizontalGroup(
            landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(community_dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search_comm_btn)
                                .addGap(175, 175, 175))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(128, 128, 128))))
                    .addGroup(landingPanelLayout.createSequentialGroup()
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(landingPanelLayout.createSequentialGroup()
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(create_new_house, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addComponent(create_hospital_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(landingPanelLayout.createSequentialGroup()
                                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(house_dropbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(update_house)))
                                    .addGroup(landingPanelLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(hospital_dropbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(update_hospital, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                                        .addComponent(update_hospital_btn)
                                        .addGap(98, 98, 98))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                                        .addComponent(update_house_btn)
                                        .addGap(97, 97, 97))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageDoctorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(managePatientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        landingPanelLayout.setVerticalGroup(
            landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(community_dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(search_comm_btn))
                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(landingPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(landingPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(hospital_dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(update_hospital_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(create_hospital_btn)
                .addGap(15, 15, 15)
                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managePatientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageDoctorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(create_new_house)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, landingPanelLayout.createSequentialGroup()
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(house_dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(update_house, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(update_house_btn)
                        .addGap(74, 74, 74))))
        );

        add(landingPanel, "card2");

        doctor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Doctor Id", "Contact No", "Doctor Name", "Age", "Community"
            }
        ));
        jScrollPane3.setViewportView(doctor_table);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Update Doctor");

        jLabel20.setText("Name:");

        jLabel21.setText("Contact No:");

        jLabel22.setText("BirthDate:");

        persontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Contact No", "BirthDate", "Community"
            }
        ));
        jScrollPane4.setViewportView(persontable);

        save_updateddoctor.setText("Save");

        add_doctorBtn.setText("Add Doctor");
        add_doctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_doctorBtnActionPerformed(evt);
            }
        });

        populatetables.setText("Populate Tables");
        populatetables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populatetablesActionPerformed(evt);
            }
        });

        hopital_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout manageDoctorsPanelLayout = new javax.swing.GroupLayout(manageDoctorsPanel);
        manageDoctorsPanel.setLayout(manageDoctorsPanelLayout);
        manageDoctorsPanelLayout.setHorizontalGroup(
            manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageDoctorsPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(doctor_name, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctor_cellno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctor_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageDoctorsPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(add_doctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(populatetables, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hopital_list, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_updateddoctor)
                .addGap(74, 74, 74))
        );
        manageDoctorsPanelLayout.setVerticalGroup(
            manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(doctor_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(doctor_cellno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(doctor_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageDoctorsPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_updateddoctor)
                    .addGroup(manageDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_doctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(populatetables, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hopital_list, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        add(manageDoctorsPanel, "card5");

        jLabel14.setText("HouseNum");

        hospNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospNum1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Zipcode");

        jLabel16.setText("City");

        jLabel17.setText("Community");

        jLabel18.setText("StreetName");

        streetNamehos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNamehosActionPerformed(evt);
            }
        });

        communityTextField1.setEditable(false);
        communityTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityTextField1ActionPerformed(evt);
            }
        });

        zipcodeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTextField1ActionPerformed(evt);
            }
        });

        saveHouseDetails.setText("Save");
        saveHouseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveHouseDetailsActionPerformed(evt);
            }
        });

        cityJTextField1.setEditable(false);
        cityJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout houseJPanelLayout = new javax.swing.GroupLayout(houseJPanel);
        houseJPanel.setLayout(houseJPanelLayout);
        houseJPanelLayout.setHorizontalGroup(
            houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseJPanelLayout.createSequentialGroup()
                .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(houseJPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipcodeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetNamehos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(houseJPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(saveHouseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(706, Short.MAX_VALUE))
        );
        houseJPanelLayout.setVerticalGroup(
            houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseJPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hospNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(streetNamehos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(communityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cityJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(houseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(zipcodeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(saveHouseDetails)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        add(houseJPanel, "card4");

        zipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTextFieldActionPerformed(evt);
            }
        });

        communityTextField.setEditable(false);
        communityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityTextFieldActionPerformed(evt);
            }
        });

        streetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameActionPerformed(evt);
            }
        });

        jLabel9.setText("StreetName");

        jLabel10.setText("Community");

        jLabel11.setText("City");

        jLabel12.setText("Zipcode");

        hospNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospNumActionPerformed(evt);
            }
        });

        jLabel13.setText("HosNum");

        cityJTextField.setEditable(false);
        cityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJTextFieldActionPerformed(evt);
            }
        });

        saveHospDetails.setText("Save");
        saveHospDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveHospDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hospitalJPanelLayout = new javax.swing.GroupLayout(hospitalJPanel);
        hospitalJPanel.setLayout(hospitalJPanelLayout);
        hospitalJPanelLayout.setHorizontalGroup(
            hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalJPanelLayout.createSequentialGroup()
                .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hospitalJPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospNum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hospitalJPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(saveHospDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(705, Short.MAX_VALUE))
        );
        hospitalJPanelLayout.setVerticalGroup(
            hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalJPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hospNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(streetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(communityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(hospitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(zipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(saveHospDetails)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        add(hospitalJPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void update_hospital_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_hospital_btnActionPerformed
        // TODO add your handling code here:

        if(hospital_table.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Please select a Hospital");
        }
        else{
            int hospNum_check= (int)model.getValueAt(hospital_table.getSelectedRow(), 0);
            String hospupdate_str = update_hospital.getText();

            for(Hospital i:community.getHospitalList()){
                if(hospNum_check == i.getHospNum()){
                    hospital = i;
                }
            }

            String hospitalUpdateCriteria = String.valueOf(hospital_dropbox.getSelectedItem());
            if(hospitalUpdateCriteria == " "){
                JOptionPane.showMessageDialog(this,"Select Valid Dropbox Item");
            }
            else{
                if(hospitalUpdateCriteria == "hospNum"){
                    int new_hospNum = Integer.parseInt(hospupdate_str);
                    hospital.setHospNum(new_hospNum);
                    populateHospTable();
                }

                if(hospitalUpdateCriteria == "streetName"){
                    String new_streetName = hospupdate_str;
                    hospital.setStreetName(new_streetName);
                    populateHospTable();
                }

                if(hospitalUpdateCriteria == "zipCode"){
                    long new_zipCode = Long.parseLong(hospupdate_str);
                    hospital.setZipcode(new_zipCode);
                    populateHospTable();
                }

            }
        }
    }//GEN-LAST:event_update_hospital_btnActionPerformed

    private void create_hospital_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_hospital_btnActionPerformed
        // TODO add your handling code here:
//        CreateNewHospital hospitalPane = new CreateNewHospital(hospital);
        //        splitPane.setRightPanel(hopitalPane);
        hospitalJPanel.setVisible(true);
        landingPanel.setVisible(false);
    }//GEN-LAST:event_create_hospital_btnActionPerformed

    private void update_house_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_house_btnActionPerformed
        // TODO add your handling code here:
        if(house_table.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Please select a House");
        }
        else{
            int houseNum_check= (int)model1.getValueAt(house_table.getSelectedRow(), 0);
            String houseupdate_str = update_house.getText();

            for(House i:community.getHouseList()){
                if(houseNum_check == i.getHouseNum()){
                    house = i;
                }
            }

            String houseUpdateCriteria = String.valueOf(house_dropbox.getSelectedItem());
            if(houseUpdateCriteria == " "){
                JOptionPane.showMessageDialog(this,"Select Valid Dropbox Item");
            }
            else{
                if(houseUpdateCriteria == "houseNum"){
                    int new_houseNum = Integer.parseInt(houseupdate_str);
                    house.setHouseNum(new_houseNum);
                    populateHouseTable();
                }

                if(houseUpdateCriteria == "streetName"){
                    String new_streetName = houseupdate_str;
                    house.setStreetName(new_streetName);
                    populateHouseTable();
                }

            }
        }

    }//GEN-LAST:event_update_house_btnActionPerformed

    private void search_comm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_comm_btnActionPerformed
        // TODO add your handling code here:
        selectedCommunity = String.valueOf(community_dropbox.getSelectedItem());

        for(Community c: city.getCommList()){
            if(selectedCommunity == c.getCommName())
            community = c;
        }

        model.setRowCount(0);
        for(Hospital h: community.getHospitalList()){
            Object[] row = new Object[5];
            row[0]= h.getHospNum();
            row[1]= h.getStreetName();
            row[2]= h.getCity();
            row[3]= h.getZipcode();
            row[4]= (h.getDoctorHospital()).size();
            model.addRow(row);
        }
        model1.setRowCount(0);
        for(House h: community.getHouseList()){
            Object[] row = new Object[4];
            row[0]= h.getHouseNum();
            row[1]= h.getStreetName();
            row[2]= h.getCity();
            row[3]= (h.getFamiliyMembers()).size();
            model1.addRow(row);
        }
        communityTextField.setText(community.getCommName());
        communityTextField1.setText(community.getCommName());
        cityJTextField.setText(city.getCitName());
        cityJTextField1.setText(city.getCitName());
        
    }
        
   public void populateHospTable(){
       for(Community c: city.getCommList()){
            if(selectedCommunity == c.getCommName())
                community = c;
        }
        
        model.setRowCount(0);
        for(Hospital h: community.getHospitalList()){
            Object[] row = new Object[5];
            row[0]= h.getHospNum();
            row[1]= h.getStreetName();
            row[2]= h.getCity();
            row[3]= h.getZipcode();
            row[4]= (h.getDoctorHospital()).size();
            model.addRow(row);
        }
}

    public void populateHouseTable(){
      for(Community c: city.getCommList()){
            if(selectedCommunity == c.getCommName())
                community = c;
        }
        
        model1.setRowCount(0);
        for(House h: community.getHouseList()){
            Object[] row = new Object[4];
            row[0]= h.getHouseNum();
            row[1]= h.getStreetName();
            row[2]= h.getCity();
            row[3]= (h.getFamiliyMembers()).size();
            model1.addRow(row);
        }
    }//GEN-LAST:event_search_comm_btnActionPerformed

    private void zipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTextFieldActionPerformed

    private void communityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityTextFieldActionPerformed

    private void streetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameActionPerformed

    private void hospNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospNumActionPerformed

    private void cityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextFieldActionPerformed

    private void saveHospDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveHospDetailsActionPerformed
        // TODO add your handling code here:
        boolean true_hospNum = false;
        int HospNum1 = Integer.parseInt(hospNum.getText());
        
        for (Hospital h:community.getHospitalList()){
            if(h.getHospNum() == HospNum1){
                JOptionPane.showMessageDialog(this,"This Hospital Already Exist");
                true_hospNum = true;
            }
        }
        
        if(!true_hospNum){
            String city1 = cityJTextField.getText();
            String streetName1 = streetName.getText();
            String community1 = communityTextField.getText();
            Long Zipcode1 =Long.parseLong(zipcodeTextField.getText());
            hospitalDirectory = new HospitalDirectory();
            hospitalDirectory.createHospital(HospNum1,streetName1,community1,city1);
            community.createHospital(HospNum1,streetName1,community1,city1);
            populateHospTable();
            JOptionPane.showMessageDialog(this,"New Hospital Created with Id: "+HospNum1);
            
            hospNum.setText("");
            cityJTextField.setText("");
            streetName.setText("");
            communityTextField.setText("");
            zipcodeTextField.setText("");
        }
//        Community cc = city.getCommList();
        
        
    }//GEN-LAST:event_saveHospDetailsActionPerformed

    private void create_new_houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_new_houseActionPerformed
        // TODO add your handling code here:
        houseJPanel.setVisible(true);
        landingPanel.setVisible(false);
    }//GEN-LAST:event_create_new_houseActionPerformed

    private void hospNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospNum1ActionPerformed

    private void streetNamehosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNamehosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNamehosActionPerformed

    private void communityTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityTextField1ActionPerformed

    private void zipcodeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTextField1ActionPerformed

    private void saveHouseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveHouseDetailsActionPerformed
        // TODO add your handling code here:
        int HospNum1 = Integer.parseInt(hospNum1.getText());
        
        boolean true_houseNum = false;
        
        for (House h:community.getHouseList()){
            if(h.getHouseNum() == HospNum1){
                JOptionPane.showMessageDialog(this,"This House Already Exist");
                true_houseNum = true;
            }
        }
        if(!true_houseNum){
            String city1 = cityJTextField1.getText();
            String streetName1 = streetNamehos.getText();
            String community1 = communityTextField1.getText();
            Long Zipcode1 =Long.parseLong(zipcodeTextField1.getText());
            community.createHouse(HospNum1,streetName1,community1,city1);
            populateHouseTable();
        
            JOptionPane.showMessageDialog(this,"New House Created with Id: "+HospNum1);

            hospNum1.setText("");
            streetNamehos.setText("");
            cityJTextField1.setText("");
            communityTextField1.setText("");
            zipcodeTextField1.setText("");
        }
        
    }//GEN-LAST:event_saveHouseDetailsActionPerformed

    private void cityJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextField1ActionPerformed

    private void managePatientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managePatientsButtonActionPerformed

    private void manageDoctorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorsButtonActionPerformed
        // TODO add your handling code here:
        manageDoctorsPanel.setVisible(true);
        landingPanel.setVisible(false);
    }//GEN-LAST:event_manageDoctorsButtonActionPerformed
     DefaultTableModel model12;
    private void populatetablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populatetablesActionPerformed
        // TODO add your handling code here:
        model12 = (DefaultTableModel) persontable.getModel();
        model12.setRowCount(0);
        
        long[] doc_cnum = new long[docDir.getDoctorList().size()];
        
        for(int i=0; i<(docDir.getDoctorList()).size(); i++){
            doc_cnum[i] = docDir.getDoctorList().get(i).getPerson().getContactNo();
            System.out.println("This Docto ss: "+docDir.getDoctorList().get(i).getPerson().getContactNo());
        }
        
        for (Person per : pd.getPersonList()) {
            boolean a = true;
            for(long i : doc_cnum){
                if(i == per.getContactNo()){
                    System.out.print("This Person is a doctor");
                    a = false;
                }
            }
            if(a == true){
                Object[] row = new Object[4];

                row[0] = per.getName();
                row[1] = per.getContactNo();
                row[2] = per.getDob();
                row[3] = per.getComm();
                model12.addRow(row);
                a = true;
            }
        }
        
        DefaultTableModel model11 = (DefaultTableModel) doctor_table.getModel();
        model11.setRowCount(0);

        
            for(Doctor dr: docDir.getDoctorList()){
                Object[] row = new Object[5];
                row[0] = dr.getId();
                row[1] = dr.getPerson().getContactNo();
                row[2] = dr.getPerson().getName();
                row[3] = dr.getPerson().getDob();
                row[4] = community.getCommName();
                model11.addRow(row);
            }
        
    }//GEN-LAST:event_populatetablesActionPerformed

    private void add_doctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_doctorBtnActionPerformed
        // TODO add your handling code here:
        if(persontable.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Please select a person to add");
        }
        if(hopital_list.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Please select a hospital to add doctor");
        }
        else
        {
            long ppn = (long)model12.getValueAt(persontable.getSelectedRow(),1);
            for(Person p : pd.getPersonList()){
                if(ppn == p.getContactNo()){
                    selectedPerson = p;
                }
            }
            
            
            for(Hospital h : hospitalDirectory.getHospitalList()){
                if(Integer.parseInt((String)hopital_list.getSelectedItem()) == h.getHospNum()){
                    selectedHospital = h;
                }
            }
            
            boolean should_doc = false;
            for(Patient p: patDir.getPatientList()){
                if(p.matchByContact(selectedPerson.getContactNo())){
                    JOptionPane.showMessageDialog(this, "This Person is a Patient and cannot become Doctor");
                    should_doc = true;
                }    
            }
            
            if(!should_doc){
                    selectedHospital.addDoctorToHospital(new Doctor(selectedPerson));
                    JOptionPane.showMessageDialog(this, "Added "+selectedPerson.getName()+ " to Hospital");
                    should_doc = false;
                    
                }
            
        }//end else
            
            
            
//            for (Hospital hos : community.getHospitalList()) {
//                
//                hos.getDoctorHospital().add(dr);
////            for(Doctor dr: hos.getDoctorHospital()){
////                
////            }
//        }
////            int hospNum_check= (int)model.getValueAt(hospital_table.getSelectedRow(), 0);
//            String hospupdate_str = update_hospital.getText();
//
//            for(Hospital i:community.getHospitalList()){
//                if(hospNum_check == i.getHospNum()){
//                    hospital = i;
//                }
//            }
        
    }//GEN-LAST:event_add_doctorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_doctorBtn;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextField cityJTextField1;
    private javax.swing.JTextField communityTextField;
    private javax.swing.JTextField communityTextField1;
    private javax.swing.JComboBox<String> community_dropbox;
    private javax.swing.JButton create_hospital_btn;
    private javax.swing.JButton create_new_house;
    private javax.swing.JTextField doctor_birthdate;
    private javax.swing.JTextField doctor_cellno;
    private javax.swing.JTextField doctor_name;
    private javax.swing.JTable doctor_table;
    private javax.swing.JComboBox<String> hopital_list;
    private javax.swing.JTextField hospNum;
    private javax.swing.JTextField hospNum1;
    private javax.swing.JPanel hospitalJPanel;
    private javax.swing.JComboBox<String> hospital_dropbox;
    private javax.swing.JTable hospital_table;
    private javax.swing.JPanel houseJPanel;
    private javax.swing.JComboBox<String> house_dropbox;
    private javax.swing.JTable house_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel landingPanel;
    private javax.swing.JButton manageDoctorsButton;
    private javax.swing.JPanel manageDoctorsPanel;
    private javax.swing.JButton managePatientsButton;
    private javax.swing.JTable persontable;
    private javax.swing.JButton populatetables;
    private javax.swing.JButton saveHospDetails;
    private javax.swing.JButton saveHouseDetails;
    private javax.swing.JButton save_updateddoctor;
    private javax.swing.JButton search_comm_btn;
    private javax.swing.JTextField streetName;
    private javax.swing.JTextField streetNamehos;
    private javax.swing.JTextField update_hospital;
    private javax.swing.JButton update_hospital_btn;
    private javax.swing.JTextField update_house;
    private javax.swing.JButton update_house_btn;
    private javax.swing.JTextField zipcodeTextField;
    private javax.swing.JTextField zipcodeTextField1;
    // End of variables declaration//GEN-END:variables
}
