/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import model.City;
import model.Community;
import model.Doctor;
import model.Hospital;
import model.HospitalDirectory;
import model.Patient;
import model.PatientDirectory;
import parser.Parser;

/**
 *
 * @author rajmehta
 */
public class HospitalAdministratorPanel extends javax.swing.JPanel {
    
    Community comm = new Community();
    Patient pat =new Patient();
    ArrayList<Community> commList;
    ArrayList<Patient> patList;
    Parser parser = new Parser();
    PatientDirectory patDir; 
    Hospital newHospital;
    ArrayList<Doctor> docs;
    String patCommunity = "";
    City city;
    Community community;
    HospitalDirectory hospDir;
    Doctor dd;
    Hospital hh;
    /**
     * Creates new form HospitalAdminstratorPanel
     */
    public HospitalAdministratorPanel(String[] communityList, PatientDirectory patDir, Hospital newHospital, City city, HospitalDirectory hospDir) {
        initComponents();
        this.patDir = patDir;
        this.newHospital = newHospital;
        this.city = city;
        this.hospDir = hospDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
