/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.Doctor;
import model.Hospital;
import model.HospitalDirectory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import parser.Parser;

/**
 *
 * @author rajmehta
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    Community comm = new Community();
    Patient pat =new Patient();
    ArrayList<Community> commList;
    ArrayList<Patient> patList;
    Parser parser = new Parser();
    PatientDirectory patDir; 
    Hospital newHospital;
    ArrayList<Doctor> docs;
    String patCommunity = "";
    City city;
    Community community;
    HospitalDirectory hospDir;
    Doctor dd;
    Hospital hh;
    
    ArrayList<Hospital> arr_hosp;
    
    public PatientPanel() {
        initComponents();  
    }
    
    public PatientPanel(String[] communityList, PatientDirectory patDir, Hospital newHospital, City city, HospitalDirectory hospDir) {
        initComponents();  
        this.patDir = patDir;
        this.newHospital = newHospital;
        this.city = city;
        this.hospDir = hospDir;
        
        doctor_community_dropbox.removeAllItems();
        
       
        for(Community commList:city.getCommList()){
            doctor_community_dropbox.addItem(commList.getCommName());
        }
        
//         for(String s:communityList){
//            doctor_community_dropbox.addItem(s);
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctor_community_dropbox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        searchDoctor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctor_table = new javax.swing.JTable();
        view_doctor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doctor_name = new javax.swing.JTextField();
        doctor_id = new javax.swing.JTextField();
        doctor_community = new javax.swing.JTextField();
        doctor_hospital = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        patient_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel1.setFont(new java.awt.Font("Zapfino", 0, 18)); // NOI18N
        jLabel1.setText("Look for a doctor under the near hospitals");

        doctor_community_dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Select Community:");

        searchDoctor.setText("Search");
        searchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDoctorActionPerformed(evt);
            }
        });

        doctor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Did", "Community", "Hospital Num"
            }
        ));
        jScrollPane1.setViewportView(doctor_table);

        view_doctor.setText("View");
        view_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_doctorActionPerformed(evt);
            }
        });

        jLabel4.setText("Name:");

        jLabel5.setText("Did:");

        jLabel6.setText("Community:");

        jLabel7.setText("Hospital:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("Patient ID:");

        jLabel9.setText("OR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doctor_community_dropbox, 0, 264, Short.MAX_VALUE)
                            .addComponent(patient_id))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(26, 26, 26)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctor_id)
                                    .addComponent(doctor_name)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctor_hospital)
                                    .addComponent(doctor_community))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchDoctor)
                            .addComponent(view_doctor))))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(doctor_community_dropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchDoctor)
                                .addGap(97, 97, 97)
                                .addComponent(view_doctor)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(doctor_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doctor_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(doctor_community, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctor_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDoctorActionPerformed
        // TODO add your handling code here:
        
        System.out.println(patient_id.getText());
        System.out.println(doctor_community_dropbox.getSelectedItem().toString());
        
        if(patient_id.getText().isEmpty() && doctor_community_dropbox.getSelectedItem().toString() == " "){
            JOptionPane.showMessageDialog(this, "Cannot keep both options empty");
        }
        else if(!patient_id.getText().isEmpty() && doctor_community_dropbox.getSelectedItem().toString() != " "){
            System.out.println("patient_id.getText(): "+patient_id.getText());
            System.out.println("doctor_community_dropbox.getSelectedItem().toString(): "+doctor_community_dropbox.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Please Use only one option");
        }
        else{
            if(!patient_id.getText().isEmpty()){
            patList = patDir.getPatientList();
            for(int i=0; i<patList.size();i++){
                System.out.println("Inside Pat Dir traversal");
                System.out.println(patList.get(i).getPerson().getName());
                if(Integer.parseInt(patient_id.getText()) == patList.get(i).getId() ){
                    Person p = patList.get(i).getPerson();
                    patCommunity = p.getComm();
                    System.out.println("Patient belongs to:"+patCommunity);
                    }     
                }
            if(patCommunity == ""){
                JOptionPane.showMessageDialog(this, "Patient not found");
            }
            else{
               
                Community a;
          
                ArrayList<Doctor> doc_hosp_comm;
                
                ArrayList<Community> arr_comm =city.getCommList();
                for(Community i : arr_comm){
                    if(i.getCommName() == patCommunity){
                         arr_hosp= i.getHospitalList();
                    }
                }
                              
                for(Hospital j:arr_hosp){
                    doc_hosp_comm = j.getDoctorHospital();
                    
                    DefaultTableModel model = (DefaultTableModel) doctor_table.getModel();
                    model.setRowCount(0);
                    
                    for(Doctor i: doc_hosp_comm){
                        Object[] row = new Object[4];
                        row[0] = i.getPerson().getName();
                        row[1] = i.getId();
                        row[2] = patCommunity;
                        row[3] = j.getHospNum();
                        model.addRow(row);
                    }
                }
         
                         
            }
            
          }//end if search by pid
            
          if(doctor_community_dropbox.getSelectedItem().toString() != " "){
              
               String searchDoctorComm = doctor_community_dropbox.getSelectedItem().toString();
               for(Community c: city.getCommList()){
                   if(c.getCommName() == searchDoctorComm)
                       community = c;
               }
               
               DefaultTableModel model = (DefaultTableModel) doctor_table.getModel();
               model.setRowCount(0);
               
               for(Hospital h: community.getHospitalList()){
                   for(Doctor d : h.getDoctorHospital()){
                       Object[] row = new Object[4];
                        row[0] = d.getPerson().getName();
                        row[1] = d.getId();
                        row[2] = searchDoctorComm;
                        row[3] = h.getHospNum();
                        model.addRow(row);
                   }
               }
          }
            
        }
   
    }//GEN-LAST:event_searchDoctorActionPerformed

    private void view_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_doctorActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = doctor_table.getSelectedRow();
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) doctor_table.getModel();
            long did = (long)model.getValueAt(doctor_table.getSelectedRow(), 1);
            for(Hospital h: hospDir.getHospitalList()){
                for(Doctor d:h.getDoctorHospital()){
                    if(d.getId() == did){
                        hh = h;
                        dd = d;
                    }
                }
            }
        
            doctor_id.setText(String.valueOf(dd.getId()));
            doctor_name.setText(String.valueOf((dd.getPerson().getName())));
            doctor_community.setText(String.valueOf(dd.getPerson().getComm()));
            doctor_hospital.setText(String.valueOf(hh.getHospNum()));
        }
    }//GEN-LAST:event_view_doctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField doctor_community;
    private javax.swing.JComboBox<String> doctor_community_dropbox;
    private javax.swing.JTextField doctor_hospital;
    private javax.swing.JTextField doctor_id;
    private javax.swing.JTextField doctor_name;
    private javax.swing.JTable doctor_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patient_id;
    private javax.swing.JButton searchDoctor;
    private javax.swing.JButton view_doctor;
    // End of variables declaration//GEN-END:variables
}
